- process:
    name: ${self:provider.stage}-${self:service}
    description: Connection Service
    handler: src/handlers/${self:provider.name}/rise-connection-service-handler.rise
    timeout: 900
    include:
      - src/handlers/${self:provider.name}/rise-connection-service-handler.js
      - node_modules/rise-connection-service/**

    events:
    - http:
        path: connection/{type}/{email_id}
        method: get
    - http:
        path: connection/{type}/{mentor_email_id}
        method: put

# RISE:
#   name: ${self:provider.stage}-rise-connection-service
#   description: rise ${self:provider.stage} 
#   handler: src/handlers/${self:provider.name}/rise-connection-service-handler.rise
#   disableLogs: true #To disable default log group creation by serverless
#   timeout: 30
#   memorySize: 512 # optional, in MB, default is 1024
#   package:
#     include:
#       - src/handlers/${self:provider.name}/rise-connection-service-handler.js
#       - node_modules/rise-connection-service/**
#   events:
#     - http:
#         path: rise/connection/{type}/{email_id}
#         method: get
#         async: false
#     #    private: true 
#     - http:
#         path: rise/connection/{mentee_email_id}/{mentor_email_id}
#         method: put
#         async: false
#         # private: true 
#     - http:
#         path: referenceData/{entity}
#         method: delete
#         async: false
#         # private: true 
    