- process:
    name: ${self:provider.stage}-${self:service}
    description: Connection Service
    handler: src/handlers/${self:provider.name}/rise-connection-service-handler.rise
    timeout: 900
    include:
      - src/handlers/${self:provider.name}/rise-connection-service-handler.js
      - node_modules/rise-connection-service/**

    events:
    - http:
        path: connection/{type}/{email_id}
        method: get
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - applicationId
            - applicationid
            - code
            - code_verifier
            - Access-Control-Allow-Headers
            - Access-Control-Request-Headers
            - Access-Control-Request-Method
            - Access-Control-Allow-Origin
        # authorizer:
        #   type: CUSTOM
        #   authorizerId:
        #     'Fn::ImportValue': mentorship-auth-ui-${opt:stage}-authorizer
    - http:
        path: connection/{type}/{email_id}
        method: put
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - applicationId
            - applicationid
            - code
            - code_verifier
            - Access-Control-Allow-Headers
            - Access-Control-Request-Headers
            - Access-Control-Request-Method
            - Access-Control-Allow-Origin
        # authorizer:
        #   type: CUSTOM
        #   authorizerId:
        #     'Fn::ImportValue': mentorship-auth-ui-${opt:stage}-authorizer
    - http:
        path: connection/{type}/{email_id}
        method: delete
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - applicationId
            - applicationid
            - code
            - code_verifier
            - Access-Control-Allow-Headers
            - Access-Control-Request-Headers
            - Access-Control-Request-Method
            - Access-Control-Allow-Origin
        # authorizer:
        #   type: CUSTOM
        #   authorizerId:
        #     'Fn::ImportValue': mentorship-auth-ui-${opt:stage}-authorizer

# RISE: 
#   name: ${self:provider.stage}-rise-connection-service
#   description: rise ${self:provider.stage} 
#   handler: src/handlers/${self:provider.name}/rise-connection-service-handler.rise
#   disableLogs: true #To disable default log group creation by serverless
#   timeout: 30
#   memorySize: 512 # optional, in MB, default is 1024
#   package:
#     include:
#       - src/handlers/${self:provider.name}/rise-connection-service-handler.js
#       - node_modules/rise-connection-service/**
#   events:
#     - http:
#         path: rise/connection/{type}/{email_id}
#         method: get
#         async: false
#     #    private: true 
#     - http:
#         path: rise/connection/{mentee_email_id}/{mentor_email_id}
#         method: put
#         async: false
#         # private: true 
#     - http:
#         path: referenceData/{entity}
#         method: delete
#         async: false
#         # private: true 
    