Resources:
  StatisticsEventHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/${opt:stage, self:provider.stage}-${self:service}
      RetentionInDays: ${self:custom.fromTerraform.pe_log_group_retention_period}