Resources:
  RiseAuditQueue:
    Type: "AWS::SQS::Queue"
    DeletionPolicy: Retain
    Properties:
      QueueName: ${opt:stage}-${self:custom.queueName}
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600   
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 180
      Tags: ${self:custom.fromTerraform.common_tags}
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt":
            - RiseAuditDeadLetterQueue
            - Arn
        maxReceiveCount: 5
  RiseAuditDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${opt:stage}-dl-${self:custom.queueName}
      MessageRetentionPeriod: 345600 # 4 days in seconds
      VisibilityTimeout: 180

  snsToRiseAuditQueueSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "allow-sns-messages"
              Effect: Allow
              Principal: "*"
              Resource: !GetAtt
                - RiseAuditQueue
                - Arn
              Action: "SQS:SendMessage"
              Condition:
                ArnEquals:
                  "aws:SourceArn": "arn:aws:sns:${self:custom.fromTerraform.region, 'eu-west-1'}:${self:custom.fromTerraform.aws_account_id, '0'}:${opt:stage}-rise-audit-topic"
        Queues:
          - Ref: "RiseAuditQueue"

  RiseAuditQueueSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "arn:aws:sns:"arn:aws:sns:${self:custom.fromTerraform.region, 'eu-west-1'}:${self:custom.fromTerraform.aws_account_id, '0'}:${self:provider.stage}-eif-audit-topic"
        Endpoint: !GetAtt
          - RiseAuditQueue
          - Arn
        # FilterPolicy:
        #   interfaceName:  []
        Protocol: sqs
        RawMessageDelivery: 'false'

  # AuditRtsLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: /aws/lambda/${opt:stage, self:provider.stage}-${self:service}
  #     RetentionInDays: ${self:custom.fromTerraform.middleware_cloudwatch_log_group_retention_period}
  # RtsUiTransformerSubscriptionFilter:
  #   Type: AWS::Logs::SubscriptionFilter
  #   Properties: 
  #     DestinationArn: arn:aws:lambda:${self:custom.fromTerraform.middleware_region, 'eu-west-1'}:${self:custom.fromTerraform.middleware_aws_account_id, '0'}:function:datadog-log-shipper-lambda-${self:provider.stage}
  #     FilterPattern: ''
  #     LogGroupName: 
  #       Ref: AuditRtsLogGroup