Resources:
  AuditSuccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/${opt:stage, self:provider.stage}-${self:service}
      RetentionInDays: 5
  # OrderDOmainServiceSubscriptionFilter:
  #   Type: AWS::Logs::SubscriptionFilter
  #   Properties: 
  #     DestinationArn: arn:aws:lambda:${self:custom.fromTerraform.region, 'eu-west-1'}:${self:custom.fromTerraform.aws_account_id, '0'}:function:datadog-log-shipper-lambda-${self:provider.stage}
  #     FilterPattern: ''
  #     LogGroupName: 
  #       Ref: OrderDOmainServiceLogGroup