  Resources:
    riseStatsDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "entity"
            AttributeType: "S"   
          - AttributeName: "operation"
            AttributeType: "S"  
        KeySchema:
          - AttributeName: "entity"
            KeyType: "HASH"
          - AttributeName: "operation"
            KeyType: "RANGE"
        BillingMode: "PAY_PER_REQUEST"
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:custom.tableName}
