RISE:
  name: ${self:provider.stage}-rise-service
  description: rise ${self:provider.stage} 
  handler: src/handlers/${self:provider.name}/rise-service-handler.rise
  disableLogs: true #To disable default log group creation by serverless
  timeout: 30
  memorySize: 512 # optional, in MB, default is 1024
  package:
    include:
      - src/handlers/${self:provider.name}/rise-service-handler.js
      - node_modules/rise-service/**
  events:
    - http:
        path: status
        method: post
        async: false
    #    private: true 
    - http:
        path: process
        method: post
        async: false
        cors:
            origin: "*"
            headers:
              - Content-Type
              - Access-Control-Allow-Headers
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Access-Control-Allow-Origin
            allowCredentials: false
        #    authorizer:
        #    type: CUSTOM
        #    authorizerId:
        #        'Fn::ImportValue': auth-ui-${opt:stage}-authorizer
        # private: true 
    - http:
        path: search
        method: post
        async: false
        # private: true 