RISE:
  name: ${self:provider.stage}-rise-service
  description: rise ${self:provider.stage} 
  handler: src/handlers/${self:provider.name}/rise-service-handler.rise
  disableLogs: true #To disable default log group creation by serverless
  timeout: 30
  memorySize: 512 # optional, in MB, default is 1024
  package:
    include:
      - src/handlers/${self:provider.name}/rise-service-handler.js
      - node_modules/rise-service/**
  events:
    - http:
        path: stats/{entity}
        method: get
        async: false
    #    private: true 
    - http:
        path: referenceData/{entity}
        method: post
        async: false
        # private: true 
    - http:
        path: referenceData/{entity}
        method: get
        async: false
        # private: true 
    - http:
        path: referenceData/{entity}
        method: put
        async: false
        # private: true 
    - http:
        path: search/{entity}
        method: get
        async: false
        # private: true 
    