'use strict';
let ExceptionType = {
	// Example: 
	'MISSING_CURRENCY': 'missingCurrency',
	'MISSING_FILENAME': 'missingFilename',
	'MISSING_RATE': 'missingRate',
	'TRANSFORMATION_FAILED': 'transformationError',
	'MISSING_FILE_ROW_DATA': 'missingFileRowData',
	'UNKNOWN_ERROR': 'unknownError',
	'ERROR_WHILE_VALIDATION': 'errorWhileValidation',
	'ERROR_WHILE_READINGFILE': 'errorWhileReadingFile',
	'ERROR_WHILE_EVALUATING_FILE': 'errorWhileEvaluatingFile',
	'ERROR_WHILE_COPYINGFILE': 'errorWhileCopyingFile',
	'ERROR_WHILE_DELETINGFILE': 'errorWhileDeletingFile',
	'ERROR_WHILE_LISTING_FILE':'errorWhileListingFile',
	'UNHANDLED_EXCEPTION':'unhandeledException',
	'ERROR_APPLYING_RULE':'errorApplyingRule',
	'UNEXPECTED_FILE_COUNT': 'unexpectedFileCount',
	'DATE_MISMATCHED': 'dateMismatched',
	'ERR_FILE_MASK_CHECK':'fileMaskCheck',
	'ERR_DUPLICATE_FILE_CHECK':'duplicateFileCheck',
	'ERR_EMPTY_FILE_CHECK':'emptyFileCheck',
	'ERR_RECORD_COUNT_CHECK':'recordCountCheck',
	'ERR_EMPTY_FILE_HEADER':'emptyHeader',
	'ERR_INVALID_TRAILER':'invalidTrailer',
	'ERR_INVALID_HEADER':'invalidHeader',
	'ERR_TRAILER_CREATION_FAILED':'trailerCreationFailed',
	'ERR_HEADER_CREATION_FAILED':'headerCreationFailed',
	'ERR_EMPTY_TRAILER':'emptyTrailer',
	'ERR_OUTPUT_FILE_NAME':'outputFileName',
	'ERR_SOURCE_TABLE_EMPTY':'emptySourceTable',
	'ERR_FILE_HEADER_LENGTH_CHECK' : 'headerLengthCheck',
	'ERR_FILE_TRAILER_LENGTH_CHECK' : 'trailerLengthCheck',
	'ERR_RECORD_LENGTH_CHECK' : 'recordLengthCheck',
	'IGNORE_ERROR':'ignoreError',
	'INVALID_MESSAGE_CODE' : 'invalidMessageCode',
	'WARNING_MESSAGE' : 'warningMessage',
	'DATABASE_CONNECTION_FAILURE': 'databaseConnectionFailure',
	'ERROR_CREATING_SCHEDULE':'errorCreatingSchedule',
	'TIMESLOT_NOTIFICATION': 'timeslotNotification',
	'ERR_EMPTY_DETAIL_RECORD': 'emptyDetailRecord',
	'MISSING_FILE': 'missingFile',
	'STATIC_DATA': 'staticData',
	'INPUT_FILE_ERROR': 'inputFileError',
	'NOVALIDRECORDSFOUND': 'novalidrecordsfound'
};

module.exports = ExceptionType;