  Resources:
    riseConnectionDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "email_id"
            AttributeType: "S"   
        KeySchema:
          - AttributeName: "email_id"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:custom.tableName}
        TimeToLiveSpecification:
          AttributeName: record_expiry
          Enabled: true
