- process:
    name: ${self:provider.stage}-${self:service}
    description: File Success Handler
    handler: src/handlers/${self:provider.name}/cloudsearch-sync-handler.handler
    reservedConcurrency: 30
    timeout: 120
    package:
      include:
        - src/handlers/${self:provider.name}/cloudsearch-sync-handler.js
        - node_modules/cloudsearch-service/**
    # events:
    # - http:
    #     path: /email/test
    #     method: get
    # - sqs:
    #     arn: arn:aws:sqs:${self:custom.fromTerraform.region, 'eu-west-1'}:${self:custom.fromTerraform.aws_account_id, '0'}:${opt:stage}-${self:custom.queueName}
    #     batchSize: 10
